# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claumeter < Formula
  desc "Interactive TUI for AI assistant token usage analysis"
  homepage "https://github.com/GerardoFC8/claumeter"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.7.1/claumeter_0.7.1_darwin_x86_64.tar.gz"
      sha256 "8d480d0e6fc3c98723b9615cce999ac493125d1a071226b5bbc88d053ec13b36"

      define_method(:install) do
        bin.install "claumeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.7.1/claumeter_0.7.1_darwin_arm64.tar.gz"
      sha256 "64614b406e430fa4c388b56a9efb38a75ac7db5409897af6b8f26fe9ca8db24e"

      define_method(:install) do
        bin.install "claumeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.7.1/claumeter_0.7.1_linux_x86_64.tar.gz"
      sha256 "605231fdd8bae1a36bf72bc832eb2e859f8e797fd9281e088aa09eac0340b3f8"
      define_method(:install) do
        bin.install "claumeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.7.1/claumeter_0.7.1_linux_arm64.tar.gz"
      sha256 "f99c24a8d7b5950f186615b609e987df34d0a3a8ac90df0ab00abea07ccbaa39"
      define_method(:install) do
        bin.install "claumeter"
      end
    end
  end

  def caveats
    <<~EOS
      To run claumeter as a background service (widgets will use it
      automatically for real-time data):

        brew services start claumeter

      Then:
        - curl http://127.0.0.1:7777/today
        - Widgets (DMS, Waybar) auto-upgrade to rich mode.

      Stop it later with `brew services stop claumeter`.
    EOS
  end

  service do
    run [opt_bin/"claumeter", "serve", "--host", "127.0.0.1", "--port", "7777"]
    keep_alive true
    log_path var/"log/claumeter.log"
    error_log_path var/"log/claumeter.err.log"
  end
end
