# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claumeter < Formula
  desc "Interactive TUI for AI assistant token usage analysis"
  homepage "https://github.com/GerardoFC8/claumeter"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.3.0/claumeter_0.3.0_darwin_x86_64.tar.gz"
      sha256 "7f20b71f0841f9b35c15060f88f48d44ff4f555437810c847bf429eb4026fa8c"

      define_method(:install) do
        bin.install "claumeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.3.0/claumeter_0.3.0_darwin_arm64.tar.gz"
      sha256 "ec06f31b71a55138c5e31131549a926f22a4af18309e8aabae4d5eba3b49a868"

      define_method(:install) do
        bin.install "claumeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.3.0/claumeter_0.3.0_linux_x86_64.tar.gz"
      sha256 "603a3b8a8ee9365dcc0d3ffaa9b59418ae5389a44c956436225e494fae3e5366"
      define_method(:install) do
        bin.install "claumeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.3.0/claumeter_0.3.0_linux_arm64.tar.gz"
      sha256 "867c165004e888747092f42e1736aae1e67ad610c4a366f7fb27b4eab716d532"
      define_method(:install) do
        bin.install "claumeter"
      end
    end
  end
end
