# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claumeter < Formula
  desc "Interactive TUI for AI assistant token usage analysis"
  homepage "https://github.com/GerardoFC8/claumeter"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.8.1/claumeter_0.8.1_darwin_x86_64.tar.gz"
      sha256 "56d0cc3b719687414b408dde2e6ee7e0b0e6126cc049b1ad08bb9cf2c6ad1e7e"

      define_method(:install) do
        bin.install "claumeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.8.1/claumeter_0.8.1_darwin_arm64.tar.gz"
      sha256 "b9b0e1c4eae031be9d69d08781d043198993eb6a329bf3d914941c5160a327ac"

      define_method(:install) do
        bin.install "claumeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.8.1/claumeter_0.8.1_linux_x86_64.tar.gz"
      sha256 "fa90be6517c54e129823a626888c798a7eefae3bb98fa90783c9ac7d2f97d861"
      define_method(:install) do
        bin.install "claumeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GerardoFC8/claumeter/releases/download/v0.8.1/claumeter_0.8.1_linux_arm64.tar.gz"
      sha256 "f826f364ef746c2ddd2bf702f8f82557b28b7a64d3a15fb90e389a444774dc87"
      define_method(:install) do
        bin.install "claumeter"
      end
    end
  end

  def caveats
    <<~EOS
      To run claumeter as a background service (widgets will use it
      automatically for real-time data):

        brew services start claumeter

      Then:
        - curl http://127.0.0.1:7777/today
        - Widgets (DMS, Waybar) auto-upgrade to rich mode.

      Stop it later with `brew services stop claumeter`.
    EOS
  end

  service do
    run [opt_bin/"claumeter", "serve", "--host", "127.0.0.1", "--port", "7777"]
    keep_alive true
    log_path var/"log/claumeter.log"
    error_log_path var/"log/claumeter.err.log"
  end
end
